version: 2.1

orbs:
  # https://circleci.com/developer/orbs/orb/circleci/python#usage-work-with-poetry
  python: circleci/python@2.1.1

jobs:

  poetry-invoke-lint:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Style Check and Linting
          command: poetry run inv lint
      - run:
          name: Type Checking
          command: poetry run inv typecheck

  integration-test:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - when:
          condition:
            # Only run this if I have triggered the pipeline to prevent malicious PRs
            equal: ["neozenith.dev@gmail.com", $CIRLCE_USERNAME]
          steps:
            
            - run:
                name: Integration Tests against Databricks Workspace
                command: poetry run inv integration-test


workflows:
  main:
    jobs:
      - poetry-invoke-lint

      - python/test:
          # Test most recent version first
          name: "Test 3.10"
          version: "3.10"
          requires: ["poetry-invoke-lint"]

      - python/test:
          # Test older compatable versions last.
          name: Test << matrix.version >>
          # It's not worth testing on other interpreters if the baseline one
          # failed. Can't run >4 jobs at a time anyhow!
          requires: ["Test 3.10"]
          matrix:
            parameters:
              version: ["3.8", "3.9"]

      - integration-test:
          name: "Databricks Workspace Integration Tests"
          requires: ["Test 3.8", "Test 3.9"]

# TODO: 
# - Build Docs
